/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sacco;

import sacco.security.login;

/**
 *
 * @author brevin
 */
public class welcome_page extends javax.swing.JFrame {

    /**
     * Creates new form welcome_page
     */
    public welcome_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        main_menu = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();
        settings = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        edit_admin = new javax.swing.JMenuItem();
        edit_customers = new javax.swing.JMenuItem();
        edit_role = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        Add = new javax.swing.JMenu();
        add_customer = new javax.swing.JMenuItem();
        add_admin = new javax.swing.JMenuItem();
        add_role = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        table_of_contents = new javax.swing.JMenu();
        show_table = new javax.swing.JMenuItem();
        refresh_table = new javax.swing.JMenuItem();
        math = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        addition = new javax.swing.JMenuItem();
        multiplication = new javax.swing.JMenuItem();
        modulus = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        minus = new javax.swing.JMenuItem();
        sort = new javax.swing.JMenu();
        ascending = new javax.swing.JMenuItem();
        descend = new javax.swing.JMenuItem();
        graph = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("welcome to Cash Money SACCO");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(1, 1));
        setState(1);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sacco/images/Pics/men.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        File.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sacco/images/folder.png"))); // NOI18N
        File.setText("File");

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sacco/images/Pics/exit.png"))); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        File.add(exit);

        settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sacco/images/Pics/job.png"))); // NOI18N
        settings.setText("Settings");
        File.add(settings);

        main_menu.add(File);

        Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sacco/images/Pics/edit.png"))); // NOI18N
        Edit.setText("Edit");

        edit_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sacco/images/Pics/edit.png"))); // NOI18N
        edit_admin.setText("Edit Admin");
        edit_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_adminActionPerformed(evt);
            }
        });
        Edit.add(edit_admin);

        edit_customers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sacco/images/Pics/edit.png"))); // NOI18N
        edit_customers.setText("Edit Customer");
        edit_customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_customersActionPerformed(evt);
            }
        });
        Edit.add(edit_customers);

        edit_role.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sacco/images/Pics/edit.png"))); // NOI18N
        edit_role.setText("Edit Role");
        edit_role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_roleActionPerformed(evt);
            }
        });
        Edit.add(edit_role);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sacco/images/Pics/edit.png"))); // NOI18N
        jMenuItem3.setText("Clear Loan");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Edit.add(jMenuItem3);

        main_menu.add(Edit);

        Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sacco/images/Pics/add.png"))); // NOI18N
        Add.setText("Add");

        add_customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sacco/images/Pics/addemployee.png"))); // NOI18N
        add_customer.setText("Add Customer");
        add_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_customerActionPerformed(evt);
            }
        });
        Add.add(add_customer);

        add_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sacco/images/Pics/addemployee.png"))); // NOI18N
        add_admin.setText("Add Administrator");
        add_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_adminActionPerformed(evt);
            }
        });
        Add.add(add_admin);

        add_role.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sacco/images/Pics/add.png"))); // NOI18N
        add_role.setText("Add Role");
        add_role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_roleActionPerformed(evt);
            }
        });
        Add.add(add_role);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sacco/images/Pics/add.png"))); // NOI18N
        jMenuItem2.setText("Add Loan");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Add.add(jMenuItem2);

        main_menu.add(Add);

        table_of_contents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sacco/images/Pics/job.png"))); // NOI18N
        table_of_contents.setText("Table of Contents");

        show_table.setText("Show Table");
        show_table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_tableActionPerformed(evt);
            }
        });
        table_of_contents.add(show_table);

        refresh_table.setText("Refresh Table");
        refresh_table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_tableActionPerformed(evt);
            }
        });
        table_of_contents.add(refresh_table);

        main_menu.add(table_of_contents);

        math.setText("Tools");

        jMenu1.setText("Mathematical equations");

        addition.setText("Add (+)");
        jMenu1.add(addition);

        multiplication.setText("Divid (/)");
        jMenu1.add(multiplication);

        modulus.setText("Modulus");
        jMenu1.add(modulus);

        jMenuItem1.setText("Multiply (x)");
        jMenu1.add(jMenuItem1);

        minus.setText("Subtract (-)");
        jMenu1.add(minus);

        math.add(jMenu1);

        sort.setText("Sort");

        ascending.setText("Ascending");
        sort.add(ascending);

        descend.setText("Descending");
        sort.add(descend);

        math.add(sort);

        graph.setText("Graph");
        math.add(graph);

        main_menu.add(math);

        setJMenuBar(main_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(118, 118, 118))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edit_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_adminActionPerformed
        
        new edit_admin().setVisible(true);
        
    }//GEN-LAST:event_edit_adminActionPerformed

    private void show_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_tableActionPerformed
        
        new table_of_results().setVisible(true);
        
    }//GEN-LAST:event_show_tableActionPerformed

    private void add_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_adminActionPerformed
        
        new Add_admin().setVisible(true);
        
    }//GEN-LAST:event_add_adminActionPerformed

    private void add_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_customerActionPerformed

//        new login().setVisible(true);
        new add_Customer().setVisible(true);

    }//GEN-LAST:event_add_customerActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        
        System.exit(0);
        
    }//GEN-LAST:event_exitActionPerformed

    private void edit_customersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_customersActionPerformed
        
        new edit_customer().setVisible(true);
        
    }//GEN-LAST:event_edit_customersActionPerformed

    private void add_roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_roleActionPerformed
        
        new Role().setVisible(true);
        
    }//GEN-LAST:event_add_roleActionPerformed

    private void edit_roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_roleActionPerformed
        
        new Role().setVisible(true);
        
    }//GEN-LAST:event_edit_roleActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        new Add_Loan().setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void refresh_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_tableActionPerformed
        
        
        
    }//GEN-LAST:event_refresh_tableActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        new Clear_Loan().setVisible(true);
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Add;
    private javax.swing.JMenu Edit;
    private javax.swing.JMenu File;
    private javax.swing.JMenuItem add_admin;
    private javax.swing.JMenuItem add_customer;
    private javax.swing.JMenuItem add_role;
    private javax.swing.JMenuItem addition;
    private javax.swing.JMenuItem ascending;
    private javax.swing.JMenuItem descend;
    private javax.swing.JMenuItem edit_admin;
    private javax.swing.JMenuItem edit_customers;
    private javax.swing.JMenuItem edit_role;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenuItem graph;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuBar main_menu;
    private javax.swing.JMenu math;
    private javax.swing.JMenuItem minus;
    private javax.swing.JMenuItem modulus;
    private javax.swing.JMenuItem multiplication;
    private javax.swing.JMenuItem refresh_table;
    private javax.swing.JMenuItem settings;
    private javax.swing.JMenuItem show_table;
    private javax.swing.JMenu sort;
    private javax.swing.JMenu table_of_contents;
    // End of variables declaration//GEN-END:variables
}